
DROP TABLE IF EXISTS ROLE_TBL;


CREATE TABLE ROLE_TBL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  ADI varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;