  CREATE TABLE USER_TOKEN_HSTRY_TBL (
  ID INT NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  USER_TOKEN_ID INT,
  USER_ID int(11) NOT NULL,
  TOKEN VARCHAR(512),
  IP VARCHAR(22),
  ROLES VARCHAR(4000),
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;