DROP TABLE IF EXISTS USER_TBL;

CREATE TABLE USER_TBL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  FIRST_NAME varchar(255) NOT NULL,
  LAST_NAME varchar(255) NOT NULL,
  PASSWORD varchar(255) NOT NULL,
  EMAIL varchar(255) NOT NULL,
  PHONEMOBIL varchar(255) null,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;